config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  root :to => 'sessions#welcome'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#index'
  get 'logout', to: 'sessions#out'

  get '/users' => 'users#new', as: 'users_new'
  post '/users' => 'users#create', as: 'users_create'

  get '/categories' => 'categories#new', as: 'categories_new'
  post '/categories' => 'categories#create', as: 'categories_create'
  delete '/categories/:id' => 'categories#delete', as: 'categories_delete'
  
  get '/categories/change/:id' => 'categories#change', as: 'categories_change'
  post '/categories/change' => 'categories#change'
  put '/categories/change/:id' => 'categories#update', as: 'categories_update'
  
  get '/tasks' => 'tasks#new'
  get '/tasks/:id' => 'tasks#new', as: 'tasks_new'
  delete '/tasks/:id' => 'tasks#delete', as: 'tasks_delete'
  put '/tasks/:id' => 'tasks#finish', as: 'tasks_finish'

  get '/tasks/new' => 'tasks#new'
  post '/tasks/new' => 'tasks#create', as: 'tasks_create'

  get '/tasks/change/:id' => 'tasks#change', as: 'tasks_change'
  post '/tasks/change' => 'tasks#change'
  put '/tasks/change/:id' => 'tasks#update', as: 'tasks_update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :category_name, presence: true

  belongs_to :user
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  validates :task_name, presence: true
  validates :due_date, presence: true

  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true,  uniqueness: true
  validates :username, presence: true,  uniqueness: true
  has_secure_password

  has_many :categories
  has_many :tasks, through: :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorized
  helper_method :current_user
  helper_method :logged_in?

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def authorized
    redirect_to '/welcome' unless logged_in?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :welcome]

  def new
    @id = session[:user_id]
    if @id == nil
      redirect_to '/authorized'
    else
      @list = Category.where(user_id:@id).sort_by {|obj| obj.category_name}
      @count = @list.count
      @category = Category.new
    end
  end

  def change
    @list = Category.where(user_id: session[:user_id]).sort_by {|obj| obj.category_name}
    @count = @list.count
    @category_id = params[:id]
    @category = Category.find_by(id: @category_id)
  end

  def create
    user = User.find_by_id(session[:user_id])
    @category = user.categories.new(category_params)
    if @category.save 
      redirect_to '/authorized'
    else
      flash[:alert] = "* Category name not set"
      redirect_to '/categories' 
    end 
  end

  def update  
    @category = Category.find_by_id(params[:id])
    tasks = Task.where(category_id:@category.id)
    if @category.update(category_params)
      new_name = @category.category_name
      tasks.update_all(category_name:new_name)
      redirect_to '/authorized'
    else
      flash[:alert] = "* Category name not set"
      redirect_to categories_change_path(@category.id)
    end
  end

  def delete  
    Category.find_by_id(params[:id]).delete
    if Task.where(category_id:params[:id]).count > 0
      Task.where(category_id:params[:id]).delete_all
      redirect_to '/authorized'
    else
      redirect_to '/authorized'
    end
  end

  private 

  def category_params
    params.require(:category).permit(:category_name,:category_details)
    #params.require(:category).permit(:category_name,:user_id,:category_details)
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :welcome]

  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/authorized'
    else
      flash[:alert] = "Invalid Username or Password"
      render :new
    end
  end

  def index
    @task_id = params[:task_id] 
    @category_id = params[:category_id] 
    if @category_id == nil
      @category = Category.where(user_id: session[:user_id]).sort_by {|obj| obj.updated_at}.reverse
      catids = @category.pluck(:id)
      task = Task.where(category_id: catids,complete: 0)
      done_task = Task.where(category_id: catids,complete: 1)
      @urgent_task = task.where("due_date <= ?", Date.today).sort_by {|obj| obj.due_date}
      @urgent_task_count = task.where("due_date <= ?", Date.today).count
      @upcoming_task = task.where("due_date > ?", Date.today).sort_by {|obj| obj.due_date}
      @upcoming_task_count = task.where("due_date > ?", Date.today).count
      @completed_task = done_task.where(complete:1).sort_by {|obj| obj.updated_at}.reverse
      @completed_task_count = done_task.where(complete:1).count
    else
      @category = Category.where(user_id: session[:user_id]).sort_by {|obj| obj.updated_at}.reverse
      @chosen_category = Category.find_by_id(@category_id)
      task = Task.where(category_id: @category_id,complete: 0)
      done_task = Task.where(category_id: @category_id,complete: 1)
      @urgent_task = task.where("due_date <= ?", Date.today).sort_by {|obj| obj.due_date}
      @urgent_task_count = task.where("due_date <= ?", Date.today).count
      @upcoming_task = task.where("due_date > ?", Date.today).sort_by {|obj| obj.due_date}
      @upcoming_task_count = task.where("due_date > ?", Date.today).count
      @completed_task = done_task.where(complete:1).sort_by {|obj| obj.updated_at}.reverse
      @completed_task_count = done_task.where(complete:1).count

      if @task_id != nil
        @chosen_task = Task.find_by_id(@task_id)
      end
    end
  end

  def login
  end

  def welcome
    if logged_in?
      redirect_to '/authorized' 
    end
  end

  def out
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :welcome]

  def new
    @category_id = params[:id]
    @task = Task.new
  end

  def change
    @task = Task.find_by_id(params[:id])
  end

  def create
    @category_id = params[:category_id]
    if @category_id == "new" 
      flash[:alert] = "Task not saved."
      redirect_to '/authorized'
    else
      @chosen_category = Category.find_by_id(@category_id)
      @task = @chosen_category.tasks.new(task_params)
      if @task.save 
        @category = Category.find_by_id(@category_id).category_name
        newtask = Task.where(category_id: @category_id).sort_by {|obj| obj.updated_at}.reverse
        newtask[0].update(category_name: @category)
        @task.errors.full_messages
        redirect_to '/authorized'
      else
        @category_id = params[:category_id]
        render :new
      end 
    end
  end

  def update  
    @task = Task.find_by_id(params[:id])
    if @task.update(task_params)
      redirect_to '/authorized'
    else
      render '/tasks/change'
    end
  end

  def delete  
    Task.find_by_id(params[:id]).delete
    redirect_to '/authorized'
  end

  def finish
    Task.find_by_id(params[:id]).update(complete:1)
    redirect_to '/authorized'
  end

  private 

  def task_params
    params.require(:task).permit(:task_name,:task_details,:due_date,:complete)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save 
      session[:user_id] = @user.id
      redirect_to '/authorized'
    else
      render :new
    end 
  end

  private

  def user_params
    params.require(:user).permit(:email,:username,:password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/change.html.erb
<head>
  <%= stylesheet_link_tag "form" %>
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Questrial&family=Indie+Flower&family=Raleway&family=Dancing+Script:wght@400;600;700&display=swap" rel="stylesheet"> 
</head>
<body>
  <%= link_to '/authorized', method: :get do %>
    <%= image_tag("pentasks.png", :class => "logo_cat") %>
  <% end %>
  <%= form_with scope: :category, method: :put, url: categories_update_path(@category.id), local: true do |f| %>
    <div class="form_layout update_layout_cat">
      <h3 class="form_title">Update Category</h3>
      <div>
        <% if !!flash[:alert] %>
          <p class="errors"><%= flash[:alert] %></p>
        <% end %>
      </div>
        
      <%= f.label :category_name, "Name", class:"textLabel" %>
      <p class="textTips">* Maximum of 12 characters</p>
      <%= f.text_field :category_name, placeholder: 'Input Category Name', value:@category.category_name, class:"textField", :maxlength => 12 %>

      <%= f.label :category_details, "Details", class:"textLabel" %>
      <p class="textTips">* Press enter to add new line</p>
      <p class="textTips">* Maximum of 50 characters</p>
      <%= f.text_area :category_details, placeholder: 'Input Category Details', value:@category.category_details, class:"textArea", :maxlength => 50 %>

      <%= f.hidden_field :user_id, value: @id %>
      <%= f.hidden_field :id, value:@category.id %>

      <%= f.submit "UPDATE CATEGORY", :class => "savebtn" %>
          
    </div>
  <% end %>

  <div class="category_layout update_list_cat">
    <p class="cat_title">Category List</p>
    <div class="cat_scroll">
      <% if @count != 0 %>
        <% @list.each do |l| %>
          <p class="list_text"> <%= l.category_name %> </p>
        <% end %>
      <% else %>
        <p class="list_text"> No categories made </p>
      <% end %>
    </div>
  </div>

  <%= image_tag("update_post.png", :class => "update_post layer", :pos => 1) %>
  <%= image_tag("filing.png", :class => "filing layer", :pos => -1) %>
  <%= javascript_pack_tag 'form.js' %>
</body>

app/views/categories/new.html.erb
<head>
  <%= stylesheet_link_tag "form" %>
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Questrial&family=Indie+Flower&family=Raleway&family=Dancing+Script:wght@400;600;700&display=swap" rel="stylesheet"> 
</head>
<body>
  <%= form_with scope: :category, url: categories_create_path, local: true do |f| %>
    <div class="form_layout add_layout_cat">
      <h3 class="form_title">New Category</h3>
      <div>
        <% if !!flash[:alert] %>
          <p class="errors"><%= flash[:alert] %></p>
        <% end %>
      </div>
      
      <%= f.label :category_name, "Name", class:"textLabel" %>
      <p class="textTips">* Maximum of 12 characters</p>
      <%= f.text_field :category_name, class:"textField", placeholder: 'Input Category Name', :maxlength => 12 %>

      <%= f.label :category_details, "Details", class:"textLabel" %>
      <p class="textTips">* Press enter to add new line</p>
      <p class="textTips">* Maximum of 50 characters</p>
      <%= f.text_area :category_details, class:"textArea", placeholder: 'Input Category Details', :maxlength => 50 %>

      <%= f.hidden_field :user_id, value: @id %>

      <%= f.submit "SAVE CATEGORY", :class => "savebtn" %>
    </div>
  <% end %>

  <%= link_to '/authorized', method: :get do %>
    <%= image_tag("pentasks.png", :class => "logo_cat") %>
  <% end %>

  <div class="category_layout add_list_cat">
    <p class="cat_title">Category List</p>
    <div class="cat_scroll">
      <% if @count != 0 %>
        <% @list.each do |l| %>
          <p class="list_text"> <%= l.category_name %> </p>
        <% end %>
      <% else %>
        <p class="list_text"> No categories made </p>
      <% end %>
    </div>
  </div>

  <%= image_tag("board.png", :class => "board_cat layer", :pos => -1) %>
  <%= image_tag("organize.png", :class => "organize_cat layer", :pos => 1) %>
  <%= javascript_pack_tag 'form.js' %>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag asset_path('favicon.png') %>
    <title>Pen Tasks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/change.html.erb
<head>
  <%= stylesheet_link_tag "form" %> 
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Questrial&family=Indie+Flower&family=Raleway&family=Dancing+Script:wght@400;600;700&display=swap" rel="stylesheet"> 
</head> 
<body>
  <%= link_to '/authorized', method: :get do %>
    <%= image_tag("pentasks.png", :class => "logo_cat") %>
  <% end %>

  <%= form_with scope: :task, method: :put, url: tasks_update_path(@task.id), local: true do |f| %>
    <div class="form_layout_task update_layout_task">
      <h3 class="form_title_task">Update Task</h3>
      <div>
        <% if @task.errors.any? %>
          <ul>
          <% @task.errors.full_messages.each do |message| %>
            <li class="errors"><%= message %></li>
          <% end %>
          </ul>
        <% end %>
      </div>
    
      <%= f.label :task_name, "Name", class:"textLabel_task" %>
      <p class="textTips_task">* Maximum of 12 characters</p>
      <%= f.text_field :task_name, class:"textField_task", placeholder: 'Input Task Name', value:@task.task_name, :maxlength => 12 %>

      <%= f.label :due_date, "Due Date", class:"textLabel_task" %>
      <%= f.date_field :due_date, class:"textField_task", value:@task.due_date, :maxlength => 15 %>

      <%= f.label :task_details, "Details", class:"textLabel_task" %>
      <p class="textTips_task">* Press enter to add new line</p>
      <p class="textTips_task">* Maximum of 500 characters</p>
      <%= f.text_area :task_details, class:"textArea_task", placeholder: 'Input Task Details', value:@task.task_details, :maxlength => 500 %>

      <%= f.hidden_field :id, value:@task.id %>
      <%= f.hidden_field :complete, value: 0 %>
      <%= hidden_field_tag(:task_id, @task.id) %>
      <%= hidden_field_tag(:category_id, @category_id) %>

      <%= f.submit "UPDATE TASK", :class => "savebtn_task" %>
    </div>
  <% end %>
    
  <%= image_tag("update_task.png", :class => "update_task layer", :pos => -1) %>
  <%= javascript_pack_tag 'form.js' %>
</body>

app/views/tasks/new.html.erb
<head>
  <%= stylesheet_link_tag "form" %>
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Questrial&family=Indie+Flower&family=Raleway&family=Dancing+Script:wght@400;600;700&display=swap" rel="stylesheet"> 
</head>
<body>
  <%= link_to '/authorized', method: :get do %>
    <%= image_tag("pentasks.png", :class => "logo_cat") %>
  <% end %>

  <%= form_with scope: :task, url: tasks_create_path, local: true do |f| %>
    <div class="form_layout_task add_layout_task">
      <h3 class="form_title_task">New Task</h3>
      <div>
        <% if @task.errors.any? %>
          <ul>
          <% @task.errors.full_messages.each do |message| %>
            <li class="errors"><%= message %></li>
          <% end %>
          </ul>
        <% end %>
      </div>
    
      <%= f.label :task_name, "Name", class:"textLabel_task" %>
      <p class="textTips_task">* Maximum of 12 characters</p>
      <%= f.text_field :task_name, class:"textField_task", placeholder: 'Input Task Name', :maxlength => 12 %>

      <%= f.label :due_date, "Due Date", class:"textLabel_task" %>
      <%= f.date_field :due_date, class:"textField_task" %>

      <%= f.label :task_details, "Details", class:"textLabel_task" %>
      <p class="textTips_task">* Press enter to add new line</p>
      <p class="textTips_task">* Maximum of 500 characters</p>
      <%= f.text_area :task_details, class:"textArea_task", placeholder: 'Input Task Details', :maxlength => 500 %>

      <%= f.hidden_field :complete, value: 0 %>
      <%= hidden_field_tag(:category_id, @category_id) %>

      <%= f.submit "SAVE TASK", :class => "savebtn_task" %>
    </div>
  <% end %>

  <%= image_tag("add_task.png", :class => "add_task layer", :pos => -1) %>
  <%= javascript_pack_tag 'form.js' %>
</body>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<head>
  <%= stylesheet_link_tag "form" %>
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Questrial&family=Indie+Flower&family=Raleway&family=Dancing+Script:wght@400;600;700&display=swap" rel="stylesheet"> 
</head>
<body>
  <%= link_to root_path, method: :get do %>
    <%= image_tag("pentasks.png", :class => "logo_cat") %>
  <% end %>

  <%= form_for @user do |f| %>
    <div class="form_layout_user add_layout_user">
      <h3 class="form_title_user">Create an Account</h3>
      <% if @user.errors.any? %>
        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li class="errors_user"><%= message %></li>
        <% end %>
        </ul>
      <% end %>
      
      <%= f.label :email, "Email", class:"textLabel_user" %>
      <%= f.email_field  :email, class:"textField_user", placeholder: 'Input Email' %>

      <%= f.label :username, "Username", class:"textLabel_user" %>
      <p class="textTips_user">* Maximum of 12 characters</p>
      <%= f.text_field :username, class:"textField_user", placeholder: 'Input Username', :maxlength => 12 %>

      <%= f.label :password, "Password", class:"textLabel_user" %>
      <%= f.password_field :password, class:"textField_user", placeholder: 'Input Password' %>

      <%= f.submit "SIGN UP", :class => "signup" %>

      <%= link_to "/login", method: :get do %>
        <p class="link_txt_log">Already have an account? <span class="link_login">Login</span></p>  
      <% end %>
    </div>
  <% end %>

  <%= image_tag("signup.png", :class => "signup_img layer", :pos => 1) %>
  <%= javascript_pack_tag 'form.js' %>
</body>